language: java
jdk:
  - openjdk12
os: linux
dist: xenial
script:
  - gradle build -x test
deploy:
  provider: heroku
  api_key:
    secure: 34b8d5a6-fb32-412f-91e7-842d4389811a
  strategy: api
  app: currency